name: Use Herald
on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  herald:
    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Apply Herald rules'
        uses: 'gagoar/use-herald-action@v2.3.0'
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          rulesLocation: '.github/herald_rule_*.json'
          base: 'java_rules_test'
      - name: Store applied rules to file
        run: echo '${{ fromJSON(steps.herald.outputs.appliedRules) }}'
